version: "3.8"
services:
  backend:
    build:
      dockerfile: Dockerfile
      target: dev
      context: ./backend
    container_name: medusa-server
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      STORE_CORS: http://localhost
      REDIS_URL: redis://cache
      CHOKIDAR_USEPOLLING: true
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
      PORT: 9000
    volumes:
      - ./backend:/app/medusa
      - backend_node_modules:/app/medusa/node_modules
    ports:
      - "9000:9000"

  admin:
    build:
      context: ./admin
      target: dev
      dockerfile: Dockerfile
    image: admin:latest
    restart: always
    depends_on:
      - backend
    container_name: medusa-admin
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    ports:
      - "7000:7000"

  postgres:
    image: postgres:10.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  storefront:
    build:
      dockerfile: Dockerfile
      target: dev
      context: ./storefront
    container_name: medusa-storefront
    restart: always
    depends_on:
      - backend
      - ./storefront:/app/storefront
      - storefront_node_modules:/app/storefront/node_modules
    ports:
      - "8000:8000"

volumes:
  storefront_node_modules:
  backend_node_modules:
