version: "3.8"
services:
  backend:
    build:
      dockerfile: Dockerfile
      target: prod
      context: ./backend
    image: backend:latest
    container_name: medusa-server
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      NODE_ENV: production
      STORE_CORS: http://localhost
      REDIS_URL: redis://cache
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
      PORT: 9000
    ports:
      - "9000:9000"

  postgres:
    restart: always
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      target: prod
    image: admin:latest
    restart: always
    depends_on:
      - backend
    container_name: medusa-admin
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    ports:
      - "7000:7000"

  storefront:
    build:
      target: prod
      context: ./storefront
      dockerfile: Dockerfile
    image: storefront:latest
    container_name: medusa-storefront
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
